import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

GPIO.setup(26,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(6,GPIO.OUT)
GPIO.setup(5,GPIO.OUT)
GPIO.setup(0,GPIO.OUT)
GPIO.setup(24,GPIO.OUT)
GPIO.setup(15,GPIO.OUT)
GPIO.setup(14,GPIO.OUT)
print "LED on"
GPIO.output(26,GPIO.HIGH)
GPIO.output(19,GPIO.HIGH)
GPIO.output(13,GPIO.HIGH)
GPIO.output(6,GPIO.HIGH)
GPIO.output(5,GPIO.HIGH)
GPIO.output(0,GPIO.HIGH)
GPIO.output(24,GPIO.HIGH)
GPIO.output(15,GPIO.HIGH)
GPIO.output(14,GPIO.HIGH)
time.sleep(10)
print "LED off"
GPIO.output(26,GPIO.LOW)
GPIO.output(19,GPIO.LOW)
GPIO.output(13,GPIO.LOW)
GPIO.output(6,GPIO.LOW)
GPIO.output(5,GPIO.LOW)
GPIO.output(0,GPIO.LOW)
GPIO.output(24,GPIO.LOW)
GPIO.output(15,GPIO.LOW)
GPIO.output(14,GPIO.LOW)
